require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CryptoWalletApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )


  target 'CryptoWalletAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.

  # WARNING: Flipper doesn't work correctly on Apple Silicon M1

  use_flipper!({ ‘Flipper’ => ‘0.85.0’ })

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end

    # attempt to add arm64 to app project
    projects = installer.aggregate_targets
    .map{ |t| t.user_project }
    .uniq{ |p| p.path }
    .push(installer.pods_project)

    arm_value = `/usr/sbin/sysctl -n hw.optional.arm64 2>&1`.to_i

    projects.each do |project|
      project.build_configurations.each do |config|
        if arm_value == 1 then
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
      end
  
      project.save()
    end
  end
end